// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAos1rRUql8puSnWznmeh6c9HPubPULlWA',
    appId: '1:1007147914172:web:776d4fa6a74f31a1cd91b9',
    messagingSenderId: '1007147914172',
    projectId: 'cardmate-37be3',
    authDomain: 'cardmate-37be3.firebaseapp.com',
    storageBucket: 'cardmate-37be3.firebasestorage.app',
    measurementId: 'G-8ST46Z17G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8OCYuhCDyGMR7IU5oIBJL-KVFT1moxHw',
    appId: '1:1007147914172:android:a52d1dd5a39821e6cd91b9',
    messagingSenderId: '1007147914172',
    projectId: 'cardmate-37be3',
    storageBucket: 'cardmate-37be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEr-s4_ZbNL0T7cjVkizpfxhSRSQ5cL4',
    appId: '1:1007147914172:ios:8adabd126e80115ccd91b9',
    messagingSenderId: '1007147914172',
    projectId: 'cardmate-37be3',
    storageBucket: 'cardmate-37be3.firebasestorage.app',
    iosBundleId: 'com.example.cardmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEr-s4_ZbNL0T7cjVkizpfxhSRSQ5cL4',
    appId: '1:1007147914172:ios:8adabd126e80115ccd91b9',
    messagingSenderId: '1007147914172',
    projectId: 'cardmate-37be3',
    storageBucket: 'cardmate-37be3.firebasestorage.app',
    iosBundleId: 'com.example.cardmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAos1rRUql8puSnWznmeh6c9HPubPULlWA',
    appId: '1:1007147914172:web:8f1bceaa8ecb8d91cd91b9',
    messagingSenderId: '1007147914172',
    projectId: 'cardmate-37be3',
    authDomain: 'cardmate-37be3.firebaseapp.com',
    storageBucket: 'cardmate-37be3.firebasestorage.app',
    measurementId: 'G-WQZP2H5QGE',
  );
}
